language: c
compiler:
  - gcc
notifications:
  email: false
env:
  matrix:
    - JULIAVERSION="juliareleases"
    - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
  - sudo apt-get install -qq cmake git gfortran libopenmpi-dev openmpi-bin
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
  - echo "--- Install MPI Wrappers ---"
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.build("MPI")'
  - echo "--- CTest Log ---"
  - cat /users/travis/.julia/v*/MPI/deps/build/Testing/Temporary/LastTest.log
  - echo "--- compile-time.jl ----"
  - cat /users/travis/.julia/v*/MPI/src/compile-time.jl
